# Generated by Django 5.1.4 on 2024-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('disease', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=100)),
            ],
        ),
    ]
